#!/usr/bin/env bash
set -o errexit -o nounset -o pipefail

# Copyright ©Sion Dafydd
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

packages=$(find . -maxdepth 3 -name PKGBUILD | cut -d'/' -f 2)

if [ "${packages}" = "" ]; then
  echo "No packages found"
  exit
fi

for pkgname in ${packages}; do
	pkgdir="./${pkgname}"

  if [ ! -d "${pkgdir}" ]; then
    echo "Package ${pkgname} not found"
    continue
  fi
  if [ ! -f "${pkgdir}/PKGBUILD" ]; then
    echo "Cannot find PKGBUILD in ${pkgdir}"
    continue
  fi

  # Build package
	cd "${pkgdir}"
	ppa-build
	cd ..
done

# vim:set ts=2 sw=2 ft=sh noet ai:
